# FATE tests for Emby ID3v2 tag parsing customizations
#
# These tests verify the behavior introduced by the following custom commits:
#   076 (e1881bc214) - Fix ID3v2 tag genre parsing
#   077 (9f8971409a) - Read full null separated list for text info frames
#   078 (68bbbe87e1) - Concatenate multi-values by semicolon
#   095 (2280b401a2) - Fix value repetition when tags are duplicated
#   104 (c7bc7fa550) - Avoid endless loop with invalid mp3 files
#   123 (6d77542d46) - Fix TCON parsing for ID3v2 version 4
#   187 (22715caf5a) - Fix mem allocation bug in parsing of ID3 tags
#
# Test data is generated by tests/emby-id3v2-gen.py which creates minimal
# MP3 files with specific ID3v2 tag structures.

EMBY_ID3V2_GEN = $(SRC_PATH)/tests/emby-id3v2-gen.py

# --- Test data generation ---

tests/data/emby-id3v2-genre-paren.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py genre-paren $(TARGET_PATH)/$@

tests/data/emby-id3v2-genre-numeric.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py genre-numeric $(TARGET_PATH)/$@

tests/data/emby-id3v2-genre-nonfull.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py genre-nonfull $(TARGET_PATH)/$@

tests/data/emby-id3v2-multivalue.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py multivalue $(TARGET_PATH)/$@

tests/data/emby-id3v2-duplicate.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py duplicate $(TARGET_PATH)/$@

tests/data/emby-id3v2-genre-multi.mp3: $(EMBY_ID3V2_GEN) | tests/data
	$(M)python3 $(SRC_PATH)/tests/emby-id3v2-gen.py genre-multi $(TARGET_PATH)/$@

tests/data/emby-id3v2-genre-paren.mp3 tests/data/emby-id3v2-genre-numeric.mp3 tests/data/emby-id3v2-genre-nonfull.mp3 tests/data/emby-id3v2-multivalue.mp3 tests/data/emby-id3v2-duplicate.mp3 tests/data/emby-id3v2-genre-multi.mp3: TAG = GEN

# --- Test 1: Parenthesized genre "(17)" resolves to "Rock" (commits 076, 123) ---
# The TCON frame contains the string "(17)". The custom read_ttag parser
# must resolve this to the genre name "Rock" via ff_id3v1_genre_str.
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-genre-paren
fate-emby-id3v2-genre-paren: tests/data/emby-id3v2-genre-paren.mp3
fate-emby-id3v2-genre-paren: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-genre-paren.mp3

# --- Test 2: Bare numeric genre "17" resolves to "Rock" in v2.4 (commit 123) ---
# ID3v2.4 stores genres as plain numbers without parentheses. The %d%n
# check (sscanf + strlen guard) must accept full-string numerics.
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-genre-numeric
fate-emby-id3v2-genre-numeric: tests/data/emby-id3v2-genre-numeric.mp3
fate-emby-id3v2-genre-numeric: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-genre-numeric.mp3

# --- Test 3: Partial numeric "17abc" NOT resolved (commit 123) ---
# The %n guard ensures that "17abc" is NOT mistakenly resolved to genre 17.
# Without the fix, sscanf("%d") would match the leading "17" and resolve
# incorrectly. The tag value must remain "17abc".
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-genre-nonfull
fate-emby-id3v2-genre-nonfull: tests/data/emby-id3v2-genre-nonfull.mp3
fate-emby-id3v2-genre-nonfull: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-genre-nonfull.mp3

# --- Test 4: Multi-value null-separated text joined by semicolons (commits 077, 078) ---
# The TPE1 frame contains "Artist1\0Artist2\0Artist3" (null-separated).
# The custom while loop + AV_DICT_APPEND must concatenate them as
# "Artist1;Artist2;Artist3".
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-multivalue
fate-emby-id3v2-multivalue: tests/data/emby-id3v2-multivalue.mp3
fate-emby-id3v2-multivalue: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-multivalue.mp3

# --- Test 5: Duplicate tag frames -- only first kept (commit 095) ---
# Two TIT2 frames with values "First" and "Second". The duplicate tag
# guard (av_dict_get check at top of read_ttag) must skip the second frame.
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-duplicate
fate-emby-id3v2-duplicate: tests/data/emby-id3v2-duplicate.mp3
fate-emby-id3v2-duplicate: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-duplicate.mp3

# --- Test 6: Multi-value genre "(17)\0(0)" → "Rock;Blues" (commits 078, 123) ---
# Combines multi-value parsing with genre resolution. Each null-separated
# genre number must be resolved independently and concatenated.
FATE_EMBY_ID3V2-$(CONFIG_MP3_DEMUXER) += fate-emby-id3v2-genre-multi
fate-emby-id3v2-genre-multi: tests/data/emby-id3v2-genre-multi.mp3
fate-emby-id3v2-genre-multi: CMD = probetags $(TARGET_PATH)/tests/data/emby-id3v2-genre-multi.mp3

# --- Collect all tests ---
FATE_EMBY_ID3V2 += $(FATE_EMBY_ID3V2-yes)
FATE_FFPROBE += $(FATE_EMBY_ID3V2)
fate-emby-id3v2: $(FATE_EMBY_ID3V2)
